### ISSUE TITLE
Kate

### ISSUE THREAD

**Issue by tim77** [flathub/org.kde.kwrite#12]
Hello. Sorry for dumb question, but is it possible to provide also Kate editor along with Kwrite? Or we should package it separately?

**Comment by hfiguiere** [comment]
Kate was removed from flathub at the request of the Kate developers.

See https://github.com/flathub/org.kde.kate/pull/23 for more details.

**Comment by tim77** [comment]
Ah, understood. @hfiguiere thanks a lot.
