### ISSUE TITLE
Question - Any plans for a Kate Flatpak?

### ISSUE THREAD

**Issue by VarLad** [flathub/org.kde.kwrite#17]
I saw one on Github but it was archived
Any plans for another try at packaging Kate with Flatpaks in the future?

**Comment by tsdgeos** [comment]
No unless you can make it work 100% like the non flatpak version.

**Comment by travier** [comment]
See the discussion in https://invent.kde.org/teams/flathub/issues/-/issues/9 for what's needed to make this happen.
