### ISSUE TITLE
just was wondering what is going to happen to this flatpak when kwrite and kate merge. 

### ISSUE THREAD

**Issue by manoflinux** [flathub/org.kde.kwrite#27]
Will this become a kate/kwrite flatpak?  I hope so, it would be nice to have access to kate as a flatpak.

**Comment by Pointedstick** [comment]
It'll stay a KWrite flatpak. If Kate gets flatpacked again, it will have its own.

**Comment by Perkolator** [comment]
> If Kate gets flatpacked again, it will have its own.

What was the reason to stop releasing Kate as Flatpak?
